#!/bin/sh
#python -m unittest UnitTesting.zola_testing.connect_dropdown_friends &&
#python -m unittest UnitTesting.zola_testing.search_test &&
#python -m unittest UnitTesting.zola_testing.sub_category_test &&
python -m unittest UnitTesting.zola_testing.activity_star.star_users_activity &&
python -m unittest UnitTesting.zola_testing.add_to_list_modal.addtolist_flow_notsignedin_test &&
python -m unittest UnitTesting.zola_testing.add_to_list_modal.addtolist_flow_signedin_test &&
python -m unittest UnitTesting.zola_testing.add_to_list_modal.addtolist_flow_signup_test &&
python -m unittest UnitTesting.zola_testing.add_to_list_profile.addtolist_flow_notsignedin_profile &&
python -m unittest UnitTesting.zola_testing.add_to_list_profile.addtolist_flow_signedin_profil &&
python -m unittest UnitTesting.zola_testing.add_to_list_profile.addtolist_flow_signup_profile &&
python -m unittest UnitTesting.zola_testing.category_dropdown_links.dropdown_art &&
python -m unittest UnitTesting.zola_testing.category_dropdown_links.dropdown_bio &&
python -m unittest UnitTesting.zola_testing.category_dropdown_links.dropdown_business &&
python -m unittest UnitTesting.zola_testing.category_dropdown_links.dropdown_children &&
python -m unittest UnitTesting.zola_testing.category_dropdown_links.dropdown_classics &&
python -m unittest UnitTesting.zola_testing.category_dropdown_links.dropdown_crafts &&
python -m unittest UnitTesting.zola_testing.category_dropdown_links.dropdown_crime &&
python -m unittest UnitTesting.zola_testing.category_dropdown_links.dropdown_criticism &&
python -m unittest UnitTesting.zola_testing.category_dropdown_links.dropdown_drama &&
python -m unittest UnitTesting.zola_testing.category_dropdown_links.dropdown_fiction &&
python -m unittest UnitTesting.zola_testing.category_dropdown_links.dropdown_graphic &&
python -m unittest UnitTesting.zola_testing.category_dropdown_links.dropdown_historical &&
python -m unittest UnitTesting.zola_testing.category_dropdown_links.dropdown_history &&
python -m unittest UnitTesting.zola_testing.category_dropdown_links.dropdown_humor &&
python -m unittest UnitTesting.zola_testing.category_dropdown_links.dropdown_litfic &&
python -m unittest UnitTesting.zola_testing.category_dropdown_links.dropdown_nonfiction &&
python -m unittest UnitTesting.zola_testing.category_dropdown_links.dropdown_parenting &&
python -m unittest UnitTesting.zola_testing.category_dropdown_links.dropdown_politics &&
python -m unittest UnitTesting.zola_testing.category_dropdown_links.dropdown_reference &&
python -m unittest UnitTesting.zola_testing.category_dropdown_links.dropdown_religion &&
python -m unittest UnitTesting.zola_testing.category_dropdown_links.dropdown_romance &&
python -m unittest UnitTesting.zola_testing.category_dropdown_links.dropdown_science &&
python -m unittest UnitTesting.zola_testing.category_dropdown_links.dropdown_scifi &&
python -m unittest UnitTesting.zola_testing.category_dropdown_links.dropdown_selfhelp &&
python -m unittest UnitTesting.zola_testing.category_dropdown_links.dropdown_travel &&
python -m unittest UnitTesting.zola_testing.category_dropdown_links.dropdown_urban &&
python -m unittest UnitTesting.zola_testing.category_dropdown_links.dropdown_ya &&
python -m unittest UnitTesting.zola_testing.connect_dropdown_links.authors &&
python -m unittest UnitTesting.zola_testing.connect_dropdown_links.booksellers &&
python -m unittest UnitTesting.zola_testing.connect_dropdown_links.curators &&
python -m unittest UnitTesting.zola_testing.connect_dropdown_links.friends_not_signed_in &&
python -m unittest UnitTesting.zola_testing.connect_dropdown_links.friends_signed_in &&
python -m unittest UnitTesting.zola_testing.connect_dropdown_links.friends_sign_up &&
python -m unittest UnitTesting.zola_testing.connect_dropdown_links.publishers &&
python -m unittest UnitTesting.zola_testing.follow_acp_list.follow_flow_notsignedin_list &&
python -m unittest UnitTesting.zola_testing.follow_acp_list.follow_flow_signedin_list &&
python -m unittest UnitTesting.zola_testing.follow_acp_list.follow_flow_signup_list &&
python -m unittest UnitTesting.zola_testing.follow_full_profile.follow_flow_notsignedin_profile &&
python -m unittest UnitTesting.zola_testing.follow_full_profile.follow_flow_signedin_profile &&
python -m unittest UnitTesting.zola_testing.follow_full_profile.follow_flow_signup_profile &&
python -m unittest UnitTesting.zola_testing.follow_modal.follow_flow_notsignedin_modal &&
python -m unittest UnitTesting.zola_testing.follow_modal.follow_flow_signedin_modal &&
python -m unittest UnitTesting.zola_testing.follow_modal.follow_flow_signup_modal &&
python -m unittest UnitTesting.zola_testing.homepage_category_links.homepage_art &&
python -m unittest UnitTesting.zola_testing.homepage_category_links.homepage_bio &&
python -m unittest UnitTesting.zola_testing.homepage_category_links.homepage_business &&
python -m unittest UnitTesting.zola_testing.homepage_category_links.homepage_children &&
python -m unittest UnitTesting.zola_testing.homepage_category_links.homepage_classics &&
python -m unittest UnitTesting.zola_testing.homepage_category_links.homepage_crafts &&
python -m unittest UnitTesting.zola_testing.homepage_category_links.homepage_crime &&
python -m unittest UnitTesting.zola_testing.homepage_category_links.homepage_criticism &&
python -m unittest UnitTesting.zola_testing.homepage_category_links.homepage_drama &&
python -m unittest UnitTesting.zola_testing.homepage_category_links.homepage_fiction &&
python -m unittest UnitTesting.zola_testing.homepage_category_links.homepage_graphic &&
python -m unittest UnitTesting.zola_testing.homepage_category_links.homepage_historical &&
python -m unittest UnitTesting.zola_testing.homepage_category_links.homepage_history &&
python -m unittest UnitTesting.zola_testing.homepage_category_links.homepage_humor &&
python -m unittest UnitTesting.zola_testing.homepage_category_links.homepage_litfic &&
python -m unittest UnitTesting.zola_testing.homepage_category_links.homepage_nonfiction &&
python -m unittest UnitTesting.zola_testing.homepage_category_links.homepage_parenting &&
python -m unittest UnitTesting.zola_testing.homepage_category_links.homepage_politics &&
python -m unittest UnitTesting.zola_testing.homepage_category_links.homepage_reference &&
python -m unittest UnitTesting.zola_testing.homepage_category_links.homepage_religion &&
python -m unittest UnitTesting.zola_testing.homepage_category_links.homepage_romance &&
python -m unittest UnitTesting.zola_testing.homepage_category_links.homepage_science &&
python -m unittest UnitTesting.zola_testing.homepage_category_links.homepage_scifi &&
python -m unittest UnitTesting.zola_testing.homepage_category_links.homepage_selfhelp &&
python -m unittest UnitTesting.zola_testing.homepage_category_links.homepage_travel &&
python -m unittest UnitTesting.zola_testing.homepage_category_links.homepage_urban &&
python -m unittest UnitTesting.zola_testing.homepage_category_links.homepage_ya &&
python -m unittest UnitTesting.zola_testing.homepage_links.all_categories &&
python -m unittest UnitTesting.zola_testing.homepage_links.bottom_about_zola &&
python -m unittest UnitTesting.zola_testing.homepage_links.bottom_contact_us &&
python -m unittest UnitTesting.zola_testing.homepage_links.bottom_copyright_icon &&
python -m unittest UnitTesting.zola_testing.homepage_links.bottom_copyright &&
python -m unittest UnitTesting.zola_testing.homepage_links.bottom_facebook &&
python -m unittest UnitTesting.zola_testing.homepage_links.bottom_help &&
python -m unittest UnitTesting.zola_testing.homepage_links.bottom_news &&
python -m unittest UnitTesting.zola_testing.homepage_links.bottom_privacy &&
python -m unittest UnitTesting.zola_testing.homepage_links.bottom_terms &&
python -m unittest UnitTesting.zola_testing.homepage_links.bottom_twitter &&
python -m unittest UnitTesting.zola_testing.homepage_links.new_releases_bio &&
python -m unittest UnitTesting.zola_testing.homepage_links.new_releases_business &&
python -m unittest UnitTesting.zola_testing.homepage_links.new_releases_fiction &&
python -m unittest UnitTesting.zola_testing.homepage_links.new_releases_history &&
python -m unittest UnitTesting.zola_testing.homepage_links.new_releases_romance &&
python -m unittest UnitTesting.zola_testing.homepage_links.new_releases_scifi &&
python -m unittest UnitTesting.zola_testing.homepage_links.new_releases_scitech &&
python -m unittest UnitTesting.zola_testing.homepage_links.new_releases_selfhelp &&
python -m unittest UnitTesting.zola_testing.homepage_links.new_releases_thrillers &&
python -m unittest UnitTesting.zola_testing.homepage_links.new_releases_ya &&
python -m unittest UnitTesting.zola_testing.homepage_links.see_all_fiction_new_releases &&
python -m unittest UnitTesting.zola_testing.homepage_links.see_all_nonfiction_new_releases &&
python -m unittest UnitTesting.zola_testing.homepage_links.side_feed_notsignedin &&
python -m unittest UnitTesting.zola_testing.homepage_links.side_feed_signedin &&
python -m unittest UnitTesting.zola_testing.homepage_links.side_feed_signup &&
python -m unittest UnitTesting.zola_testing.homepage_links.side_more_zola_bestsellers &&
python -m unittest UnitTesting.zola_testing.homepage_links.side_nyt_bestsellers &&
python -m unittest UnitTesting.zola_testing.homepage_links.side_people_finder_notsignedin &&
python -m unittest UnitTesting.zola_testing.homepage_links.side_people_finder_signedin &&
python -m unittest UnitTesting.zola_testing.homepage_links.side_people_finder_signup &&
python -m unittest UnitTesting.zola_testing.homepage_links.side_usa_today_bestsellers &&
python -m unittest UnitTesting.zola_testing.homepage_links.user_in_the_feed &&
python -m unittest UnitTesting.zola_testing.homepage_links.wishlist_notsignedin &&
python -m unittest UnitTesting.zola_testing.homepage_links.wishlist_signedin &&
python -m unittest UnitTesting.zola_testing.homepage_links.wishlist_signup &&
python -m unittest UnitTesting.zola_testing.homepage_links.zola_exclusives &&
python -m unittest UnitTesting.zola_testing.homepage_links.zola_network_notsignedin &&
python -m unittest UnitTesting.zola_testing.homepage_links.zola_network_signedin &&
python -m unittest UnitTesting.zola_testing.homepage_links.zola_network_signup &&
python -m unittest UnitTesting.zola_testing.message.user_message &&
python -m unittest UnitTesting.zola_testing.my_ebook_links.all_books_see_all &&
python -m unittest UnitTesting.zola_testing.my_ebook_links.purchased_see_all &&
python -m unittest UnitTesting.zola_testing.my_ebook_links.wishlist_see_all &&
python -m unittest UnitTesting.zola_testing.my_zola_links.billing_info &&
python -m unittest UnitTesting.zola_testing.my_zola_links.collection_book_link &&
python -m unittest UnitTesting.zola_testing.my_zola_links.collection_tab &&
python -m unittest UnitTesting.zola_testing.my_zola_links.edit_profile &&
python -m unittest UnitTesting.zola_testing.my_zola_links.find_people &&
python -m unittest UnitTesting.zola_testing.my_zola_links.followers_tab &&
python -m unittest UnitTesting.zola_testing.my_zola_links.following_tab &&
python -m unittest UnitTesting.zola_testing.my_zola_links.list_tab &&
python -m unittest UnitTesting.zola_testing.my_zola_links.messages_tab &&
python -m unittest UnitTesting.zola_testing.my_zola_links.profile_picture &&
python -m unittest UnitTesting.zola_testing.my_zola_links.sort_everything &&
python -m unittest UnitTesting.zola_testing.my_zola_links.sort_just_me &&
python -m unittest UnitTesting.zola_testing.my_zola_links.starred_tab &&
python -m unittest UnitTesting.zola_testing.pledge_full_profile.pledge_flow_notsignedin_profile_test &&
python -m unittest UnitTesting.zola_testing.pledge_full_profile.pledge_flow_signedin_profile_test &&
python -m unittest UnitTesting.zola_testing.pledge_full_profile.pledge_flow_signup_profile_test &&
python -m unittest UnitTesting.zola_testing.pledge_modal.pledge_flow_notsignedin_test &&
python -m unittest UnitTesting.zola_testing.pledge_modal.pledge_flow_signedin_test &&
python -m unittest UnitTesting.zola_testing.pledge_modal.pledge_flow_signup_test &&
python -m unittest UnitTesting.zola_testing.purchase_book_list.purchase_flow_notsignedincc_list &&
python -m unittest UnitTesting.zola_testing.purchase_book_list.purchase_flow_notsignedin_list &&
python -m unittest UnitTesting.zola_testing.purchase_book_list.purchase_flow_signedincc_list &&
python -m unittest UnitTesting.zola_testing.purchase_book_list.purchase_flow_signedin_list &&
python -m unittest UnitTesting.zola_testing.purchase_book_list.purchase_flow_signup_list &&
python -m unittest UnitTesting.zola_testing.purchase_full_profile.purchase_flow_notsignedincc_profil &&
python -m unittest UnitTesting.zola_testing.purchase_full_profile.purchase_flow_notsignedin_profile &&
python -m unittest UnitTesting.zola_testing.purchase_full_profile.purchase_flow_signedincc_profile &&
python -m unittest UnitTesting.zola_testing.purchase_full_profile.purchase_flow_signedin_profile &&
python -m unittest UnitTesting.zola_testing.purchase_full_profile.purchase_flow_signup_profile &&
python -m unittest UnitTesting.zola_testing.purchase_modal.purchase_flow_notsignedincc_modal &&
python -m unittest UnitTesting.zola_testing.purchase_modal.purchase_flow_notsignedin_modal &&
python -m unittest UnitTesting.zola_testing.purchase_modal.purchase_flow_signedincc_modal &&
python -m unittest UnitTesting.zola_testing.purchase_modal.purchase_flow_signedin_modal &&
python -m unittest UnitTesting.zola_testing.purchase_modal.purchase_flow_signup_modal &&
python -m unittest UnitTesting.zola_testing.rating_book_list.rating_flow_notsignedin_list &&
python -m unittest UnitTesting.zola_testing.rating_book_list.rating_flow_signedin_list &&
python -m unittest UnitTesting.zola_testing.rating_book_list.rating_flow_signup_list &&
python -m unittest UnitTesting.zola_testing.rating_full_profile.rating_flow_notsignedin_profile &&
python -m unittest UnitTesting.zola_testing.rating_full_profile.rating_flow_signedin_profile &&
python -m unittest UnitTesting.zola_testing.rating_full_profile.rating_flow_signup_profile &&
python -m unittest UnitTesting.zola_testing.rating_modal.rating_flow_notsignedin_modal &&
python -m unittest UnitTesting.zola_testing.rating_modal.rating_flow_signedin_modal &&
python -m unittest UnitTesting.zola_testing.rating_modal.rating_flow_signup_modal &&
python -m unittest UnitTesting.zola_testing.recommend_full_profile.recommend_flow_notsignedin_profile &&
python -m unittest UnitTesting.zola_testing.recommend_full_profile.recommend_flow_signedin_profil &&
python -m unittest UnitTesting.zola_testing.recommend_full_profile.recommend_flow_signup_profil &&
python -m unittest UnitTesting.zola_testing.recommend_modal.recommend_flow_notsignedin_modal &&
python -m unittest UnitTesting.zola_testing.recommend_modal.recommend_flow_signedin_modal &&
python -m unittest UnitTesting.zola_testing.recommend_modal.recommend_flow_signup_modal &&
python -m unittest UnitTesting.zola_testing.your_collection_links.all_rated &&
python -m unittest UnitTesting.zola_testing.your_collection_links.edit_devices &&
python -m unittest UnitTesting.zola_testing.your_collection_links.favorites &&
python -m unittest UnitTesting.zola_testing.your_collection_links.not_for_me &&
python -m unittest UnitTesting.zola_testing.your_collection_links.open_book_modal &&
python -m unittest UnitTesting.zola_testing.your_collection_links.preordered &&
python -m unittest UnitTesting.zola_testing.your_collection_links.private_books &&
python -m unittest UnitTesting.zola_testing.your_collection_links.purchased &&
python -m unittest UnitTesting.zola_testing.your_collection_links.view_all &&
python -m unittest UnitTesting.zola_testing.your_collection_links.wishlist &&
python -m unittest UnitTesting.zola_testing.homepage_links.navigation_bar_links.about_zola &&
python -m unittest UnitTesting.zola_testing.homepage_links.navigation_bar_links.bestsellers &&
python -m unittest UnitTesting.zola_testing.homepage_links.navigation_bar_links.deals &&
python -m unittest UnitTesting.zola_testing.homepage_links.navigation_bar_links.find_great_ebooks &&
python -m unittest UnitTesting.zola_testing.homepage_links.navigation_bar_links.house_icon &&
python -m unittest UnitTesting.zola_testing.homepage_links.navigation_bar_links.my_ebooks &&
python -m unittest UnitTesting.zola_testing.homepage_links.navigation_bar_links.my_zola &&
python -m unittest UnitTesting.zola_testing.homepage_links.navigation_bar_links.new_releases &&
python -m unittest UnitTesting.zola_testing.my_ebook_links.top_menu.lists &&
python -m unittest UnitTesting.zola_testing.my_ebook_links.top_menu.preordered &&
python -m unittest UnitTesting.zola_testing.my_ebook_links.top_menu.purchased &&
python -m unittest UnitTesting.zola_testing.my_ebook_links.top_menu.rated &&
python -m unittest UnitTesting.zola_testing.my_ebook_links.top_menu.want_to_read
